version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-trans
    hostname: my-rabbit
    ports:
      - '15672:15672'
      - '5672:5672'
    environment:
      RABBITMQ_DEFAULT_VHOST: my_vhost
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password123

  transactionapi:
    depends_on:
      - rabbitmq
    image: transactionapi
    build: ./TransactionApi
    environment:
      - RMQ_URL=amqp://admin:password123@rabbitmq:5672/my_vhost
      - TRANSACTION_QUEUE=transaction_api.order
      - ADMIN_QUEUE=admin_api.order_received
      - EMAIL_QUEUE=email_api.order_received
